create table if not exists public.product_intelligence_cache (
  id bigint generated by default as identity primary key,
  cache_key text not null unique,
  payload jsonb not null default '{}'::jsonb,
  fetched_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '1 day')
);
create index if not exists product_intelligence_cache_expires_idx on public.product_intelligence_cache(expires_at);

create table if not exists public.api_provider_usage (
  id bigint generated by default as identity primary key,
  provider text not null,
  operation text not null,
  requests integer not null default 0,
  last_used_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  unique(provider, operation)
);

create table if not exists public.comparison_usage (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  comparison_count integer not null default 0,
  free_limit integer not null default 5,
  reset_at timestamptz not null default (now() + interval '30 days'),
  unique(user_id)
);

alter table public.product_intelligence_cache enable row level security;
alter table public.api_provider_usage enable row level security;
alter table public.comparison_usage enable row level security;

revoke all on public.product_intelligence_cache from anon, authenticated;
revoke all on public.api_provider_usage from anon, authenticated;
revoke all on public.comparison_usage from anon, authenticated;

grant select, insert, update, delete on public.product_intelligence_cache to service_role;
grant select, insert, update, delete on public.api_provider_usage to service_role;
grant select, insert, update, delete on public.comparison_usage to service_role;

notify pgrst, 'reload schema';
