"use client";
import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import Link from "next/link";
import type { User } from "@supabase/supabase-js";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import { createClient } from "@/app/lib/supabase-browser";

type TrackResult={order_number:string;status:string;total:number;created_at:string;items:any[];payment_method?:string|null};
const statusSteps=["طلب جديد","قيد التواصل","تم التأكيد","قيد التجهيز","خرج للتوصيل","تم التسليم"];
const statusIcons=["🛒","💬","✓","📦","🚚","🏠"];
const statusText:Record<string,string>={"طلب جديد":"استلمنا طلبك وعم نراجع التفاصيل.","قيد التواصل":"فريقنا عم يتواصل معك لتأكيد الطلب.","تم التأكيد":"تم تأكيد الطلب وعم نجهزه للتنفيذ.","قيد التجهيز":"طلبك حالياً قيد التجهيز.","خرج للتوصيل":"طلبك صار بالطريق إليك.","تم التسليم":"تم تسجيل الطلب كمُسلّم.","ملغي":"تم إلغاء الطلب."};
export default function TrackOrderPage(){
 const s=createClient(); const[user,setUser]=useState<User|null>(null); const[orders,setOrders]=useState<TrackResult[]>([]); const[selected,setSelected]=useState<TrackResult|null>(null); const[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const{data}=await s.auth.getUser();setUser(data.user);if(data.user){const r=await s.from("orders").select("order_number,status,total,created_at,items,payment_method").eq("user_id",data.user.id).order("created_at",{ascending:false});const list=(r.data??[]) as TrackResult[];setOrders(list);setSelected(list[0]??null)}setLoading(false)})()},[s]);
 if(loading)return <><Header/><main className="py-24 text-center text-sm text-ink-soft" dir="rtl">جاري فتح التتبع...</main><Footer/></>;
 if(!user)return <><Header/><main className="mx-auto max-w-md px-4 py-24 text-center" dir="rtl"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-blue/10 text-3xl">🚚</div><h1 className="mt-5 text-2xl font-extrabold">تتبع طلبك</h1><p className="mt-2 text-sm text-ink-soft">سجّل دخول حتى يفتح معك تتبع طلباتك مباشرة، بدون رقم طلب أو رقم هاتف.</p><Link href="/login?next=/track" className="mt-6 inline-block rounded-full bg-blue px-7 py-3 font-bold text-white">تسجيل الدخول</Link></main><Footer/></>;
 const idx=selected?statusSteps.indexOf(selected.status):-1;
 return <><Header/><main className="mx-auto max-w-5xl px-4 py-10 sm:px-6" dir="rtl"><div className="flex flex-wrap items-end justify-between gap-3"><div><span className="text-xs font-extrabold tracking-widest text-blue">ORDER / LIVE TRACKING</span><h1 className="mt-2 text-3xl font-extrabold">تتبع طلباتك 🚚</h1><p className="mt-2 text-sm text-ink-soft">التتبع مفتوح مباشرة من حسابك — ما عاد في داعي تدخل رقم الطلب أو رقم الهاتف.</p></div><Link href="/purchase-history" className="rounded-full border border-line px-4 py-2 text-xs font-bold">سجل الشراء</Link></div>
 {orders.length===0?<div className="mt-8 rounded-3xl border border-dashed border-line bg-surface p-12 text-center"><div className="text-4xl">📦</div><h2 className="mt-3 text-xl font-extrabold">ما عندك طلبات حالياً</h2><p className="mt-2 text-sm text-ink-soft">لما تعمل أول طلب، رح يظهر التتبع هون تلقائياً.</p><Link href="/laptops" className="mt-5 inline-block rounded-full bg-blue px-6 py-3 text-sm font-bold text-white">تصفح اللابتوبات</Link></div>:<div className="mt-8 grid gap-5 lg:grid-cols-[.78fr_1.22fr]"><section className="rounded-3xl border border-line bg-white p-4 shadow-sm"><h2 className="px-2 text-sm font-extrabold">طلبات الحساب</h2><div className="mt-3 space-y-2">{orders.map(o=><button key={o.order_number} onClick={()=>setSelected(o)} className={`w-full rounded-2xl border p-4 text-right transition ${selected?.order_number===o.order_number?"border-blue bg-blue/10":"border-line bg-surface hover:border-blue/40"}`}><div className="flex items-center justify-between gap-3"><span className="font-mono-data text-sm font-bold text-blue">{o.order_number}</span><span className="rounded-full bg-white px-2.5 py-1 text-[10px] font-bold">{o.status}</span></div><div className="mt-2 flex items-center justify-between text-xs text-ink-soft"><span>{new Date(o.created_at).toLocaleDateString("ar-SY")}</span><b>${Number(o.total).toFixed(2)}</b></div></button>)}</div></section>
 <motion.section key={selected?.order_number} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="rounded-3xl border border-line bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="text-[10px] font-bold text-ink-soft">ORDER</span><h2 className="font-mono-data mt-1 text-xl font-extrabold text-blue">{selected?.order_number}</h2><p className="mt-1 text-xs text-ink-soft">{selected?.payment_method==="wallet"?"💳 الدفع من المحفظة":"💵 الدفع عند الاستلام"}</p></div><b className="text-2xl">${Number(selected?.total??0).toFixed(2)}</b></div><div className="mt-6 rounded-2xl bg-surface p-4"><b>{selected?.status}</b><p className="mt-1 text-sm leading-6 text-ink-soft">{statusText[selected?.status||""]||"تم تحديث حالة طلبك."}</p></div><div className="mt-6 space-y-2">{statusSteps.map((step,i)=><div key={step} className={`flex items-center gap-3 rounded-2xl p-3 ${i<=idx?"bg-blue/10":"bg-surface/60"}`}><motion.span className="flex h-10 w-10 items-center justify-center rounded-full bg-white text-lg shadow-sm" animate={i===idx?{y:[0,-3,0]}:{y:0}} transition={{duration:1.6,repeat:i===idx?Infinity:0}}>{statusIcons[i]}</motion.span><div><b className="text-sm">{step}</b>{i===idx&&<small className="mt-0.5 block text-[10px] font-bold text-blue">الحالة الحالية</small>}</div></div>)}</div><div className="mt-6 rounded-2xl border border-line p-4"><h3 className="font-extrabold">محتويات الطلب</h3><div className="mt-3 space-y-2">{(selected?.items??[]).map((item:any,i:number)=><div key={i} className="flex items-center justify-between rounded-xl bg-surface p-3 text-xs"><span>{item.name||"منتج"} × {item.qty??1}</span><b>${(Number(item.price||0)*Number(item.qty||1)).toFixed(2)}</b></div>)}</div></div></motion.section></div>}
 </main><Footer/></>;
}
