"use client";
import { useEffect, useState } from "react";
import { createClient } from "@/app/lib/supabase-browser";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import AIChat from "@/app/components/AIChat";
type ContactChannel={name:string;icon:string;href:string;text:string;value?:string};
const defaults:ContactChannel[]=[{name:"واتساب",icon:"◉",href:"https://wa.me/963936426605",text:"رد مباشر على واتساب"},{name:"تيليغرام",icon:"✈",href:"https://t.me/NexCode9",text:"تواصل عبر تيليغرام"},{name:"الإيميل",icon:"✉",href:"mailto:ibrahimbkkari51@gmail.com",text:"للاستفسارات والطلبات"}];
export default function ContactPage(){const [aiOpen,setAiOpen]=useState(false);const [channels,setChannels]=useState(defaults);useEffect(()=>{createClient().from("site_settings").select("value").eq("key","contact").maybeSingle().then((result: { data: { value: unknown } | null })=>{const c=result.data?.value as Record<string, unknown> | null;if(!c)return;setChannels([{...defaults[0],href:typeof c.whatsapp === "string" && c.whatsapp ? `https://wa.me/${c.whatsapp}` : defaults[0].href,value:typeof c.phone === "string" ? c.phone : ""},{...defaults[1],href:typeof c.telegram === "string" && c.telegram ? `https://t.me/${c.telegram.replace(/^@/,"")}` : defaults[1].href,value:typeof c.telegram === "string" ? c.telegram : ""},{...defaults[2],href:typeof c.email === "string" && c.email ? `mailto:${c.email}` : defaults[2].href,value:typeof c.email === "string" ? c.email : ""}])})},[]);return <><Header/><main className="info-page" dir="rtl"><div className="info-wrap"><div className="info-hero"><span>CONTACT / SUPPORT</span><h1>تواصل معنا</h1><p>اختار الطريقة اللي بتناسبك. وإذا بدك مساعدة فورية، افتح المساعد الذكي.</p></div><section className="contact-grid"><button onClick={()=>setAiOpen(true)} className="contact-ai-card"><div className="info-icon">✦</div><div><span>AI ASSISTANT</span><h2>شات مباشر مع المساعد</h2><p>اسأل عن اللابتوبات، الخدمات، الطلبات ومعلومات المتجر.</p></div><b>←</b></button>{channels.map(c=><a key={c.name} href={c.href} target={c.href.startsWith("http")?"_blank":undefined} rel="noreferrer" className="contact-card"><div className="info-icon">{c.icon}</div><h2>{c.name}</h2><p>{c.text}</p><span>فتح القناة ←</span></a>)}</section><section className="support-note"><div><span>SUPPORT TEAM</span><h2>بدك تحكي مع شخص من الفريق؟</h2><p>اختار واتساب أو تيليغرام أو الإيميل، ومنتابع معك حسب نوع الطلب.</p></div><a href="https://wa.me/963936426605" target="_blank" rel="noreferrer">تواصل مع الدعم</a></section></div></main>{aiOpen&&<div className="contact-ai-overlay" onClick={()=>setAiOpen(false)}><div onClick={e=>e.stopPropagation()} className="contact-ai-modal"><button onClick={()=>setAiOpen(false)} className="contact-ai-close">×</button><AIChat embedded/></div></div>}<Footer/></>}
