"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
type Field={key:string;label:string;type:string;required?:boolean;options?:string[]|null};
type Product={id:string;name:string;price:number;currencySymbol:string;minQuantity:number;maxQuantity:number;customFields:Field[]};
export default function DigitalServiceOrder({product}:{product:Product}){
 const [values,setValues]=useState<Record<string,string>>({}); const [quantity,setQuantity]=useState(Math.max(1,product.minQuantity||1)); const [confirmed,setConfirmed]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [success,setSuccess]=useState<any>(null);
 const fields=product.customFields?.length?product.customFields:[{key:"playerid",label:"ID الخاص بك",type:"text",required:true}]; const total=useMemo(()=>product.price*quantity,[product.price,quantity]);
 async function submit(e:React.FormEvent){e.preventDefault();setError("");if(!confirmed){setError("لازم تأكد إن الـID والمعلومات المدخلة صحيحة قبل إرسال الطلب.");return;}for(const f of fields){if(f.required!==false&&!String(values[f.key]??"").trim()){setError(`عبّي الحقل: ${f.label}`);return;}}setLoading(true);try{const r=await fetch("/api/satofill/order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({productId:product.id,quantity,customFields:values})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"تعذر إنشاء الطلب");setSuccess(j);}catch(e){setError(e instanceof Error?e.message:"تعذر إنشاء الطلب")}finally{setLoading(false)}}
 if(success)return <div className="rounded-3xl border border-emerald-200 bg-emerald-50 p-5"><div className="text-3xl">✅</div><h3 className="mt-2 text-lg font-extrabold text-emerald-800">تم تأكيد الطلب</h3><p className="mt-2 text-sm leading-6 text-emerald-700">تم إرسال الخدمة مباشرة. الحالة: <b>{success.status}</b>.</p><p className="mt-2 text-xs text-emerald-700">رقم الطلب: <b>{success.orderNumber}</b> · رقم الخدمة: <b>{success.satofillOrderId}</b></p><Link href="/digital-orders" className="mt-4 inline-flex rounded-full bg-blue px-5 py-2.5 text-sm font-bold text-white">فتح سجل الخدمات ←</Link></div>;
 return <form onSubmit={submit} className="space-y-4 rounded-3xl border border-blue/15 bg-surface p-5"><div><p className="text-xs font-extrabold tracking-wider text-blue">طلب مباشر — بدون سلة</p><h3 className="mt-1 text-lg font-extrabold text-ink">أدخل معلومات الخدمة</h3><p className="mt-1 text-xs leading-5 text-ink-soft">الحقل المطلوب بيظهر حسب الخدمة. تأكد من الـID قبل التأكيد.</p></div>{fields.map(f=><label key={f.key} className="block"><span className="mb-1.5 block text-xs font-bold text-ink">{f.label}{f.required!==false?" *":""}</span>{f.type==="dropdown"&&f.options?.length?<select value={values[f.key]||""} onChange={e=>setValues(v=>({...v,[f.key]:e.target.value}))} className="w-full rounded-2xl border border-line bg-white px-4 py-3 text-sm outline-none focus:border-blue"><option value="">اختار</option>{f.options.map(o=><option key={o} value={o}>{o}</option>)}</select>:<input type={f.type==="number"?"number":"text"} value={values[f.key]||""} onChange={e=>setValues(v=>({...v,[f.key]:e.target.value}))} className="w-full rounded-2xl border border-line bg-white px-4 py-3 text-sm outline-none focus:border-blue" placeholder={f.label}/>}</label>)}{product.maxQuantity>product.minQuantity&&<div className="flex items-center justify-between rounded-2xl border border-line bg-white p-3"><span className="text-xs font-bold">الكمية</span><div className="flex items-center gap-3"><button type="button" onClick={()=>setQuantity(q=>Math.max(product.minQuantity,q-1))} className="h-8 w-8 rounded-full border">−</button><b>{quantity}</b><button type="button" onClick={()=>setQuantity(q=>Math.min(product.maxQuantity,q+1))} className="h-8 w-8 rounded-full border">+</button></div></div>}<label className="flex cursor-pointer items-start gap-3 rounded-2xl border border-line bg-white p-4"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} className="mt-1 h-4 w-4"/><span className="text-xs leading-6 text-ink-soft">تأكدت من الـID والمعلومات المدخلة وأوافق على إرسال الطلب مباشرة.</span></label>{error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-3 text-xs font-semibold text-red-700">{error}</div>}<div className="flex items-center justify-between rounded-2xl bg-white p-4"><span className="text-xs text-ink-soft">الإجمالي من المحفظة</span><b className="text-xl">{product.currencySymbol}{total.toFixed(2)}</b></div><button disabled={loading} className="w-full rounded-full bg-blue px-6 py-3.5 text-sm font-extrabold text-white disabled:opacity-60">{loading?"جاري تأكيد الطلب...":"✓ تأكيد الطلب"}</button></form>;
}
