"use client";
import { useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { createClient } from "@/app/lib/supabase-browser";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import { Suspense } from "react";
const fallback={title:"الشروط والأحكام",body:"باستخدام Bkkari Tech، يوافق المستخدم على تقديم معلومات صحيحة عند إنشاء الحساب أو الطلب، وعلى مراجعة تفاصيل المنتج والسعر قبل تأكيد الطلب. الأسعار والتوفر قد تتغير قبل تأكيد الطلب من الإدارة. الخدمات الرقمية بعد تنفيذها قد لا تكون قابلة للاسترجاع إذا تم استخدامها أو تنفيذها بشكل صحيح. يمنع إساءة استخدام الموقع أو محاولة الوصول إلى حسابات أو بيانات غير مصرح بها. يحق للإدارة التواصل مع المستخدم لتأكيد الطلب ومعلومات التسليم."};
function TermsContent(){const router=useRouter();const params=useSearchParams();const acceptMode=params.get("accept")==="1";const next=params.get("next")||"/account";const s=createClient();const [content,setContent]=useState(fallback);const [accepted,setAccepted]=useState(false);const [saving,setSaving]=useState(false);useEffect(()=>{s.from("site_settings").select("value").eq("key","terms").maybeSingle().then((result: { data: { value: unknown } | null })=>{const value=result.data?.value;if(value && typeof value === "object")setContent({...fallback,...(value as Partial<typeof fallback>)})})},[s]);async function accept(){if(!accepted)return;setSaving(true);const {error}=await s.auth.updateUser({data:{terms_accepted_at:new Date().toISOString()}});setSaving(false);if(error){alert(error.message);return}router.replace(next.startsWith("/")?next:"/account")}return <><Header/><main className="policy-page" dir="rtl"><div className="policy-wrap"><div className="policy-head"><span>LEGAL / TERMS</span><h1>{content.title}</h1></div><article className="policy-card"><p>{content.body}</p></article>{acceptMode&&<section className="terms-accept-card"><h2>قبل المتابعة</h2><p>لازم توافق على الشروط والأحكام حتى تقدر تكمل استخدام الحساب.</p><label><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/> قرأت الشروط والأحكام وأوافق عليها.</label><button disabled={!accepted||saving} onClick={accept}>{saving?"جاري الحفظ...":"موافق والمتابعة"}</button></section>}</div></main><Footer/></>}
export default function TermsPage(){return <Suspense fallback={<main className="policy-page"><div className="policy-wrap">جاري التحميل...</div></main>}><TermsContent/></Suspense>}
