"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { supabase } from "@/app/lib/supabase";
import type { Laptop } from "@/app/lib/types";

type Pref = { uses:string[]; priorities:string[]; weight:string; screen:string[]; performance:string; gaming:string; mobility:string; budget:string };
type ResearchItem = { query:string; summary:string; facts?:Record<string, unknown>; sources?:Array<{provider:string;title:string;url?:string}>; prices?:Array<{seller?:string;price?:number;currency?:string;url?:string}> };
const initial: Pref = { uses:[], priorities:[], weight:"medium", screen:[], performance:"strong", gaming:"medium", mobility:"medium", budget:"value" };
const questions = [
  ["uses","شو رح تستخدم اللابتوب؟",["ألعاب 🎮","برمجة 💻","دراسة 📚","تصميم ومونتاج 🎨","شغل 🧑‍💼","ذكاء اصطناعي 🤖","استخدام يومي 🏠","متنوع 🔀"],true],
  ["priorities","شو أهم شي عندك؟",["الأداء ⚡","السعر 💰","البطارية 🔋","الشاشة 🖥️","الوزن 🎒","جودة التصنيع 🛠️"],true],
  ["weight","قديش الوزن بيفرق معك؟",["مو مهم","مهم","مهم جداً"],false],
  ["screen","شو بهمك بالشاشة؟",["عادية 👍","ألوان ودقة 🎨","تردد عالي للألعاب 🎮","دقة عالية ✨"],true],
  ["performance","قديش بدك أداء؟",["خفيف","متوسط","قوي","أقصى أداء 🔥"],false],
  ["gaming","قديش الألعاب مهمة؟",["ما بلعب","خفيفة","متوسطة","ثقيلة 🎮"],false],
  ["mobility","قديش البطارية والتنقل مهمين؟",["مو مهم","مهم","مهم جداً"],false],
  ["budget","شو موقفك من السعر؟",["أرخص خيار","أفضل قيمة مقابل السعر","عندي ميزانية محددة"],false],
] as const;
function norm(v:string){ return v.toLowerCase().normalize("NFKD").replace(/[ً-ٰٟ]/g,"").replace(/[أإآ]/g,"ا").replace(/ة/g,"ه").replace(/ى/g,"ي").replace(/ؤ/g,"و").replace(/ئ/g,"ي").replace(/[^\p{L}\p{N}]+/gu," ").trim(); }
function matches(l:Laptop,q:string){ const a=norm(`${l.name} ${l.brand||""} ${l.model||""} ${l.cpu||""} ${l.gpu||""}`), b=norm(q); const aliases=[["apple","ابل"],["asus","اسوس"],["acer","ايسر"],["lenovo","لينوفو"],["dell","ديل"],["hp","اتش بي"],["msi","ام اس اي"],["macbook","ماك بوك"],["gaming","العاب"],["laptop","لابتوب"]]; return b.split(" ").filter(Boolean).every(t=>a.includes(t)||aliases.some(([en,ar])=>(t===norm(en)||t===norm(ar))&&(a.includes(norm(en))||a.includes(norm(ar))))); }
function firstNumber(v:unknown){ const m=String(v??"").match(/\d+(?:[.,]\d+)?/); return m?Number(m[0].replace(",",".")):0; }
function gpuScore(v:unknown){const t=String(v||"").toLowerCase(); if(/rtx\s*50/.test(t))return 14;if(/rtx\s*40/.test(t))return 12;if(/rtx\s*30/.test(t))return 10;if(/rtx/.test(t)||/rx\s*[567]/.test(t))return 8;if(/gtx\s*16/.test(t))return 6;if(/gtx/.test(t))return 5;return 0;}
function cpuScore(v:unknown){const t=String(v||"").toLowerCase(); if(/i9|ultra\s*9|ryzen\s*9/.test(t))return 9;if(/i7|ultra\s*7|ryzen\s*7/.test(t))return 7;if(/i5|ultra\s*5|ryzen\s*5/.test(t))return 5;if(/i3|ryzen\s*3/.test(t))return 3;return 1;}
function ramScore(v:unknown){return Math.min(12,Math.floor(firstNumber(v)/2));}
function storageScore(v:unknown){const t=String(v||"").toLowerCase();const n=firstNumber(t);return /nvme|ssd/.test(t)?Math.min(10,5+Math.floor(n/500)):Math.min(5,1+Math.floor(n/500));}
function screenScore(l:Laptop){const t=`${l.screen_resolution||""} ${l.screen_size||""}`.toLowerCase();let s=0;if(/4k|2160|uhd/.test(t))s+=6;else if(/2k|qhd|1440|1600/.test(t))s+=5;else if(/fhd|1080|1920/.test(t))s+=4;if(/120|144|165|240|360/.test(t))s+=3;return s;}
function batteryScore(v:unknown){const n=firstNumber(v);return n?Math.min(15,n/7):0;}
function performance(l:Laptop){return cpuScore(l.cpu)+gpuScore(l.gpu)+ramScore(l.ram)+storageScore(l.storage);}
function batteryText(l:Laptop,research:ResearchItem[]){
  const own=research.find(r=>norm(r.query).includes(norm(l.name)) || norm(r.query).includes(norm(`${l.brand||""} ${l.model||""}`)));
  const text=own?.summary||"";
  const matches=text.match(/(?:battery life|battery lasts|lasts up to|up to)\D{0,40}(\d+(?:\.\d+)?)\s*(?:hours|hrs|hour|h)\b/gi)||[];
  const hours=matches[0]?.match(/(\d+(?:\.\d+)?)/)?.[1];
  return hours?`حوالي ${hours} ساعات بحسب المعلومات الخارجية المتاحة.`:`مدة التشغيل بالساعات غير موثقة حالياً؛ الموجود لدينا هو حالة البطارية: ${l.battery_health||"غير مذكورة"}.`;
}
function winnerLabel(a:Laptop,b:Laptop,sa:number,sb:number){return sa===sb?"متقارب":sa>sb?a.name:b.name;}

export default function CompareAnotherLaptop({ current }: { current: Laptop }) {
  const [open,setOpen]=useState(false), [laptops,setLaptops]=useState<Laptop[]>([]), [query,setQuery]=useState(""), [other,setOther]=useState<Laptop|null>(null), [step,setStep]=useState(0), [pref,setPref]=useState<Pref>(initial), [busy,setBusy]=useState(false), [result,setResult]=useState<any>(null), [quota,setQuota]=useState<any>(null), [message,setMessage]=useState("");
  useEffect(()=>{ if(!open)return; (async()=>{ const {data}=await supabase.from("laptops").select("*").neq("id",current.id).order("id",{ascending:false}).limit(100); setLaptops((data||[]) as Laptop[]); const r=await fetch("/api/intelligence/usage"); const u=await r.json(); setQuota(u.comparison); })(); },[open,current.id]);
  const filtered=useMemo(()=>{const list=laptops.filter(l=>Boolean(l.images?.[0])); return query.trim()?list.filter(l=>matches(l,query)):list;},[laptops,query]);
  function choose(key:string,value:string,multi:boolean){setPref(p=>{const c=(p as any)[key]; return {...p,[key]:multi?(Array.isArray(c)?(c.includes(value)?c.filter((x:string)=>x!==value):[...c,value]):[value]):value};});}
  async function run(){ if(!other)return; setBusy(true); setMessage(""); const map=(v:string)=>v.replace(/ 🎮| 💻| 📚| 🎨| 🧑‍💼| 🤖| 🏠| 🔀| ⚡| 💰| 🔋| 🖥️| 🎒| 🛠️| ✨| 🔥/g,""); const uses=pref.uses.map(v=>({"ألعاب":"gaming","برمجة":"programming","دراسة":"study","تصميم ومونتاج":"design","شغل":"work","ذكاء اصطناعي":"ai","استخدام يومي":"daily","متنوع":"mixed"}[map(v)]||map(v))); const priorities=pref.priorities.map(v=>({"الأداء":"performance","السعر":"price","البطارية":"battery","الشاشة":"screen","الوزن":"weight","جودة التصنيع":"build"}[map(v)]||map(v))); const translated={uses,priorities,weight:({"مو مهم":"low","مهم":"medium","مهم جداً":"high"}[map(pref.weight)]||pref.weight),screen:pref.screen.map(v=>({"عادية":"normal","ألوان ودقة":"color","تردد عالي للألعاب":"gaming-refresh","دقة عالية":"resolution"}[map(v)]||map(v))),performance:({"خفيف":"light","متوسط":"medium","قوي":"strong","أقصى أداء":"maximum"}[map(pref.performance)]||pref.performance),gaming:({"ما بلعب":"none","خفيفة":"light","متوسطة":"medium","ثقيلة":"heavy"}[map(pref.gaming)]||pref.gaming),mobility:({"مو مهم":"low","مهم":"medium","مهم جداً":"high"}[map(pref.mobility)]||pref.mobility),budget:({"أرخص خيار":"lowest","أفضل قيمة مقابل السعر":"value","عندي ميزانية محددة":"fixed"}[map(pref.budget)]||pref.budget)}; try{ const r=await fetch("/api/compare",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids:[current.id,other.id],preferences:translated})}); const data=await r.json(); if(!r.ok){setMessage(data.error||"تعذر إجراء المقارنة حالياً.");return;} setResult(data); setQuota(data.quota); }catch{setMessage("المقارنة مشغولة حالياً 🤖 جرّب مرة ثانية.");}finally{setBusy(false);} }
  function close(){setOpen(false);setStep(0);setOther(null);setResult(null);setQuery("");setMessage("");}
  const comparison = result?.winnerId && other ? [current,other] : [];
  const research:ResearchItem[] = Array.isArray(result?.research)?result.research:[];
  const winner = comparison.find(l=>l.id===result?.winnerId) || current;
  const loser = comparison.find(l=>l.id!==winner.id) || other;
  const rows = comparison.length===2 ? [
    {icon:"⚙️",label:"المعالج",a:String(current.cpu||"غير مذكور"),b:String(other?.cpu||"غير مذكور"),sa:cpuScore(current.cpu),sb:cpuScore(other?.cpu),why:"المعالج يحدد سرعة تنفيذ البرامج وتعدد المهام، خصوصاً بالبرامج الثقيلة."},
    {icon:"🎮",label:"كرت الشاشة",a:String(current.gpu||"غير مذكور"),b:String(other?.gpu||"غير مذكور"),sa:gpuScore(current.gpu),sb:gpuScore(other?.gpu),why:"كرت الشاشة هو العامل الأهم بالألعاب والمونتاج والتصميم ثلاثي الأبعاد."},
    {icon:"🧠",label:"الرام",a:String(current.ram||"غير مذكور"),b:String(other?.ram||"غير مذكور"),sa:ramScore(current.ram),sb:ramScore(other?.ram),why:"الرام الأكبر يساعد على تعدد المهام وفتح برامج أكثر بدون اختناق سريع."},
    {icon:"💾",label:"التخزين",a:String(current.storage||"غير مذكور"),b:String(other?.storage||"غير مذكور"),sa:storageScore(current.storage),sb:storageScore(other?.storage),why:"نوع القرص يؤثر على سرعة الإقلاع والبرامج، والسعة تحدد كمية الملفات والألعاب."},
    {icon:"🖥️",label:"الشاشة",a:[current.screen_size,current.screen_resolution].filter(Boolean).join(" • ")||"غير مذكور",b:[other?.screen_size,other?.screen_resolution].filter(Boolean).join(" • ")||"غير مذكور",sa:screenScore(current),sb:screenScore(other!),why:"الحجم والدقة ومعدل التحديث يفرقون بالراحة والألعاب والتصميم."},
    {icon:"🔋",label:"البطارية",a:batteryText(current,research),b:batteryText(other!,research),sa:batteryScore(current.battery_health),sb:batteryScore(other?.battery_health),why:"حالة البطارية تعطي فكرة عن صحتها، أما ساعات الاستخدام فتختلف حسب السطوع والألعاب والبرامج."},
    {icon:"💰",label:"السعر",a:`$${Number(current.price||0).toFixed(0)}`,b:`$${Number(other?.price||0).toFixed(0)}`,sa:Number(other?.price||0)>Number(current.price||0)?1:2,sb:Number(current.price||0)>Number(other?.price||0)?1:2,why:"الأفضل سعراً ليس بالضرورة الأقوى؛ لذلك نربط السعر بالأداء والاستخدام المطلوب."},
  ]:[];
  return <>{<button type="button" onClick={()=>setOpen(true)} className="compare-another-btn">⚖️ مقارنة مع جهاز آخر</button>}{open&&<div className="compare-question-overlay" dir="rtl"><div className={`compare-question-modal compare-new-modal ${result?.winnerId?"compare-rich-result-modal":""}`}><button className="compare-close" onClick={close}>×</button>{result?.winnerId?<div className="compare-result compare-result-final">
    <div className="compare-winner-glow">🏆</div><h3>النتيجة المناسبة إلك</h3><h2>{winner.name}</h2><strong>{result.winnerScore}/100</strong>
    <p className="compare-main-reason">{result.reason||`اخترنا ${winner.name} لأنه الأنسب لتفضيلاتك الحالية.`}</p>
    <p className="compare-quota-note">بقي معك {result.quota?.remaining ?? 0} من 10 مقارنات هالشهر.</p>
    <div className="compare-device-pair">{comparison.map(l=><article key={l.id} className={l.id===winner.id?"is-winner":""}><img src={l.images?.[0]} alt={l.name}/><span>{l.brand||"NOVATEK"}</span><h3>{l.name}</h3><b>${Number(l.price||0).toFixed(0)}</b>{l.id===winner.id&&<em>✓ الفائز</em>}</article>)}</div>
    <section className="compare-rich-summary"><h3>ليش {winner.name} هو الأفضل إلك؟</h3><p>{winner.name} تفوّق لأن عنده أفضلية أوضح في النقاط المرتبطة باستخدامك. مو بس الرقم النهائي: تحت رح تشوف شو الفرق بكل قطعة وليش بتفرق.</p>{result.warnings?.length>0&&<div className="compare-warnings">⚠️ {result.warnings.join(" • ")}</div>}</section>
    <section className="compare-spec-table"><h3>المواصفات كاملة</h3><div className="compare-spec-head"><span>المواصفة</span><b>{current.name}</b><b>{other?.name}</b></div>{[
      ["الماركة",current.brand||"غير مذكور",other?.brand||"غير مذكور"],["الموديل",current.model||"غير مذكور",other?.model||"غير مذكور"],["المعالج",current.cpu||"غير مذكور",other?.cpu||"غير مذكور"],["كرت الشاشة",current.gpu||"غير مذكور",other?.gpu||"غير مذكور"],["الرام",current.ram||"غير مذكور",other?.ram||"غير مذكور"],["التخزين",current.storage||"غير مذكور",other?.storage||"غير مذكور"],["الشاشة",[current.screen_size,current.screen_resolution].filter(Boolean).join(" • ")||"غير مذكور",[other?.screen_size,other?.screen_resolution].filter(Boolean).join(" • ")||"غير مذكور"],["حالة البطارية",current.battery_health||"غير مذكورة",other?.battery_health||"غير مذكورة"],["السعر",`$${Number(current.price||0).toFixed(0)}`,`$${Number(other?.price||0).toFixed(0)}`]
    ].map(([label,a,b])=><div className="compare-spec-row" key={String(label)}><span>{label}</span><b>{a}</b><b>{b}</b></div>)}</div></section>
    <section className="compare-breakdown"><h3>بشو أحسن؟ وليش؟</h3>{rows.map(r=>{const win=r.sa===r.sb?"متقارب":r.sa>r.sb?current.name:other?.name;return <article key={r.label}><div className="compare-breakdown-title"><span>{r.icon} {r.label}</span><strong>{win}</strong></div><div className="compare-breakdown-values"><div className={r.sa>r.sb?"better":""}><b>{current.name}</b><span>{r.a}</span></div><div className={r.sb>r.sa?"better":""}><b>{other?.name}</b><span>{r.b}</span></div></div><p><b>ليش بتفرق؟</b> {r.why}</p>{r.label==="البطارية"&&<p><b>مدة الاستخدام:</b> {batteryText(winner,research)}</p>}</article>})}</section>
    <section className="compare-use-cards"><h3>مين أنسب لكل استخدام؟</h3><div><article><b>🎮 الألعاب</b><p>{gpuScore(current.gpu)>=gpuScore(other?.gpu)?current.name:other?.name} — بسبب كرت الشاشة الأقوى، وهو العامل الأهم بأداء الألعاب.</p></article><article><b>💻 البرمجة والعمل</b><p>{cpuScore(current.cpu)+ramScore(current.ram)>=cpuScore(other?.cpu)+ramScore(other?.ram)?current.name:other?.name} — بسبب مزيج المعالج والرام الأفضل لتعدد المهام.</p></article><article><b>🎨 التصميم والمونتاج</b><p>{gpuScore(current.gpu)+screenScore(current)>=gpuScore(other?.gpu)+screenScore(other!)?current.name:other?.name} — كرت الشاشة والشاشة أهم نقطتين هون.</p></article><article><b>🔋 التنقل</b><p>{batteryScore(current.battery_health)>=batteryScore(other?.battery_health)?current.name:other?.name} — بناءً على حالة البطارية المسجلة؛ ساعات الاستخدام الفعلية تعتمد على الاستخدام.</p></article></div></section>
    <section className="compare-final-verdict"><span>🏆 الحكم النهائي</span><h3>{winner.name} أفضل إلك، والسبب مو بس لأنه أخذ {result.winnerScore}/100.</h3><p>{result.reason||"لأنه حقق تطابقاً أفضل مع أولوياتك."} أما {loser?.name} فممكن يكون أفضل إذا تغيّرت أولويتك نحو نقطة يتفوق فيها.</p></section>
    {research.length>0&&<section className="compare-sources"><h3>🔎 معلومات خارجية استخدمناها</h3>{research.map((r,i)=><div key={i}><b>{r.query}</b><p>{r.summary?.slice(0,700)}</p>{r.sources?.slice(0,4).map((s,j)=><a key={j} href={s.url||"#"} target="_blank" rel="noreferrer">{s.title} ↗</a>)}</div>)}</section>}
    <div className="compare-result-actions"><Link href={`/compare?ids=${current.id},${other?.id}`} className="compare-full-link">فتح المقارنة الكاملة ←</Link><button type="button" className="compare-restart" onClick={()=>{setResult(null);setStep(0);}}>مقارنة ثانية</button></div>
  </div>:step===0?<><span>⚖️ مقارنة ذكية</span><h2>اختار الجهاز الثاني</h2><p>ابحث بالاسم أو الماركة بالعربي أو الإنكليزي، مثل: آبل، ابل، Apple، أسوس، ASUS.</p><div className="compare-search-box"><span>🔎</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث عن جهاز أو ماركة..." autoFocus/></div><div className="compare-second-grid">{filtered.slice(0,30).map(l=><button type="button" key={l.id} className={`compare-second-card ${other?.id===l.id?"selected":""}`} onClick={()=>setOther(l)}><img src={l.images?.[0]} alt={l.name}/><span>{l.brand}</span><b>{l.name}</b><strong>${l.price}</strong></button>)}</div><div className="compare-question-actions"><button type="button" onClick={close}>إلغاء</button><button type="button" disabled={!other} onClick={()=>setStep(1)}>التالي ←</button></div></>:<><span>السؤال {step}/{questions.length}</span><h2>{questions[step-1][1]}</h2><p>اختياراتك هي اللي بتحدد وزن كل نقطة بالنتيجة.</p><div className="compare-options">{questions[step-1][2].map(v=>{const key=questions[step-1][0] as keyof Pref;const c=(pref as any)[key];const active=Array.isArray(c)?c.includes(v):c===v;return <button key={v} type="button" className={active?"active":""} onClick={()=>choose(key,v,questions[step-1][3])}>{v}</button>})}</div>{message&&<div className="compare-error">⚠️ {message}</div>}<div className="compare-question-actions"><button type="button" onClick={()=>setStep(step-1)}>رجوع</button>{step<questions.length?<button type="button" onClick={()=>setStep(step+1)}>التالي ←</button>:<button type="button" disabled={busy} onClick={run}>{busy?"عم حلل الجهازين…":"🏆 جاهز للمقارنة"}</button>}</div><p className="compare-quota-note">رصيدك: {quota?.remaining ?? 10} من 10 مقارنات هالشهر.</p></>}</div></div>}</>;
}
