"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { supabase } from "@/app/lib/supabase";
import type { Laptop } from "@/app/lib/types";

type Pref = { uses:string[]; priorities:string[]; weight:string; screen:string[]; performance:string; gaming:string; mobility:string; budget:string };
const initial: Pref = { uses:[], priorities:[], weight:"medium", screen:[], performance:"strong", gaming:"medium", mobility:"medium", budget:"value" };
const questions = [
  ["uses","شو رح تستخدم اللابتوب؟",["ألعاب 🎮","برمجة 💻","دراسة 📚","تصميم ومونتاج 🎨","شغل 🧑‍💼","ذكاء اصطناعي 🤖","استخدام يومي 🏠","متنوع 🔀"],true],
  ["priorities","شو أهم شي عندك؟",["الأداء ⚡","السعر 💰","البطارية 🔋","الشاشة 🖥️","الوزن 🎒","جودة التصنيع 🛠️"],true],
  ["weight","قديش الوزن بيفرق معك؟",["مو مهم","مهم","مهم جداً"],false],
  ["screen","شو بهمك بالشاشة؟",["عادية 👍","ألوان ودقة 🎨","تردد عالي للألعاب 🎮","دقة عالية ✨"],true],
  ["performance","قديش بدك أداء؟",["خفيف","متوسط","قوي","أقصى أداء 🔥"],false],
  ["gaming","قديش الألعاب مهمة؟",["ما بلعب","خفيفة","متوسطة","ثقيلة 🎮"],false],
  ["mobility","قديش البطارية والتنقل مهمين؟",["مو مهم","مهم","مهم جداً"],false],
  ["budget","شو موقفك من السعر؟",["أرخص خيار","أفضل قيمة مقابل السعر","عندي ميزانية محددة"],false],
] as const;
function norm(v:string){ return v.toLowerCase().normalize("NFKD").replace(/[\u064B-\u065F\u0670]/g,"").replace(/[أإآ]/g,"ا").replace(/ة/g,"ه").replace(/ى/g,"ي").replace(/ؤ/g,"و").replace(/ئ/g,"ي").replace(/[^\p{L}\p{N}]+/gu," ").trim(); }
function matches(l:Laptop,q:string){ const a=norm(`${l.name} ${l.brand||""} ${l.model||""} ${l.cpu||""} ${l.gpu||""}`), b=norm(q); const aliases=[ ["apple","ابل"],["asus","اسوس"],["acer","ايسر"],["lenovo","لينوفو"],["dell","ديل"],["hp","اتش بي"],["msi","ام اس اي"],["macbook","ماك بوك"],["gaming","العاب"],["laptop","لابتوب"] ]; return b.split(" ").filter(Boolean).every(t=>a.includes(t) || aliases.some(([en,ar])=>(t===norm(en)||t===norm(ar))&&(a.includes(norm(en))||a.includes(norm(ar))))); }

export default function CompareAnotherLaptop({ current }: { current: Laptop }) {
  const [open,setOpen]=useState(false), [laptops,setLaptops]=useState<Laptop[]>([]), [query,setQuery]=useState(""), [other,setOther]=useState<Laptop|null>(null), [step,setStep]=useState(0), [pref,setPref]=useState<Pref>(initial), [busy,setBusy]=useState(false), [result,setResult]=useState<any>(null), [quota,setQuota]=useState<any>(null), [message,setMessage]=useState("");
  useEffect(()=>{ if(!open)return; (async()=>{ const {data}=await supabase.from("laptops").select("*").neq("id",current.id).order("id",{ascending:false}).limit(100); setLaptops((data||[]) as Laptop[]); const r=await fetch("/api/intelligence/usage"); const u=await r.json(); setQuota(u.comparison); })(); },[open,current.id]);
  const filtered=useMemo(()=>{const list=laptops.filter(l=>Boolean(l.images?.[0])); return query.trim()?list.filter(l=>matches(l,query)):list;},[laptops,query]);
  function choose(key:string,value:string,multi:boolean){setPref(p=>{const c=(p as any)[key]; return {...p,[key]:multi?(Array.isArray(c)?(c.includes(value)?c.filter((x:string)=>x!==value):[...c,value]):[value]):value};});}
  async function run(){ if(!other)return; setBusy(true); setMessage(""); const map=(v:string)=>v.replace(/ 🎮| 💻| 📚| 🎨| 🧑‍💼| 🤖| 🏠| 🔀| ⚡| 💰| 🔋| 🖥️| 🎒| 🛠️| ✨| 🔥/g,""); const uses=pref.uses.map(v=>({"ألعاب":"gaming","برمجة":"programming","دراسة":"study","تصميم ومونتاج":"design","شغل":"work","ذكاء اصطناعي":"ai","استخدام يومي":"daily","متنوع":"mixed"}[map(v)]||map(v))); const priorities=pref.priorities.map(v=>({"الأداء":"performance","السعر":"price","البطارية":"battery","الشاشة":"screen","الوزن":"weight","جودة التصنيع":"build"}[map(v)]||map(v))); const translated={uses,priorities,weight:({"مو مهم":"low","مهم":"medium","مهم جداً":"high"}[map(pref.weight)]||pref.weight),screen:pref.screen.map(v=>({"عادية":"normal","ألوان ودقة":"color","تردد عالي للألعاب":"gaming-refresh","دقة عالية":"resolution"}[map(v)]||map(v))),performance:({"خفيف":"light","متوسط":"medium","قوي":"strong","أقصى أداء":"maximum"}[map(pref.performance)]||pref.performance),gaming:({"ما بلعب":"none","خفيفة":"light","متوسطة":"medium","ثقيلة":"heavy"}[map(pref.gaming)]||pref.gaming),mobility:({"مو مهم":"low","مهم":"medium","مهم جداً":"high"}[map(pref.mobility)]||pref.mobility),budget:({"أرخص خيار":"lowest","أفضل قيمة مقابل السعر":"value","عندي ميزانية محددة":"fixed"}[map(pref.budget)]||pref.budget)}; try{ const r=await fetch("/api/compare",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids:[current.id,other.id],preferences:translated})}); const data=await r.json(); if(!r.ok){setMessage(data.error||"تعذر إجراء المقارنة حالياً.");return;} setResult(data); setQuota(data.quota); }catch{setMessage("المقارنة مشغولة حالياً 🤖 جرّب مرة ثانية.");}finally{setBusy(false);} }
  function close(){setOpen(false);setStep(0);setOther(null);setResult(null);setQuery("");setMessage("");}
  return <>{<button type="button" onClick={()=>setOpen(true)} className="compare-another-btn">⚖️ مقارنة مع جهاز آخر</button>}{open&&<div className="compare-question-overlay" dir="rtl"><div className="compare-question-modal compare-new-modal"><button className="compare-close" onClick={close}>×</button>{result?.winnerId?<div className="compare-result compare-result-final"><div className="compare-winner-glow">🏆</div><h3>النتيجة المناسبة إلك</h3><h2>{result.winnerId===current.id?current.name:other?.name}</h2><strong>{result.winnerScore}/100</strong><p>{result.reason}</p>{result.warnings?.length>0&&<small>{result.warnings.join(" • ")}</small>}<p className="compare-quota-note">بقي معك {result.quota?.remaining ?? 0} من 10 مقارنات هالشهر.</p><Link href={`/compare?ids=${current.id},${other?.id}`} className="compare-full-link">شوف الفرق بالتفصيل ←</Link><button type="button" className="compare-restart" onClick={()=>{setResult(null);setStep(0);}}>مقارنة ثانية</button></div>:step===0?<><span>⚖️ مقارنة ذكية</span><h2>اختار الجهاز الثاني</h2><p>ابحث بالاسم أو الماركة بالعربي أو الإنكليزي، مثل: آبل، ابل، Apple، أسوس، ASUS.</p><div className="compare-search-box"><span>🔎</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث عن جهاز أو ماركة..." autoFocus/></div><div className="compare-second-grid">{filtered.slice(0,30).map(l=><button type="button" key={l.id} className={`compare-second-card ${other?.id===l.id?"selected":""}`} onClick={()=>setOther(l)}><img src={l.images?.[0]} alt={l.name}/><span>{l.brand}</span><b>{l.name}</b><strong>${l.price}</strong></button>)}</div><div className="compare-question-actions"><button type="button" onClick={close}>إلغاء</button><button type="button" disabled={!other} onClick={()=>setStep(1)}>التالي ←</button></div></>:<><span>السؤال {step}/{questions.length}</span><h2>{questions[step-1][1]}</h2><p>اختياراتك هي اللي بتحدد وزن كل نقطة بالنتيجة.</p><div className="compare-options">{questions[step-1][2].map(v=>{const key=questions[step-1][0] as keyof Pref;const c=(pref as any)[key];const active=Array.isArray(c)?c.includes(v):c===v;return <button key={v} type="button" className={active?"active":""} onClick={()=>choose(key,v,questions[step-1][3])}>{v}</button>})}</div>{message&&<div className="compare-error">⚠️ {message}</div>}<div className="compare-question-actions"><button type="button" onClick={()=>setStep(step-1)}>رجوع</button>{step<questions.length?<button type="button" onClick={()=>setStep(step+1)}>التالي ←</button>:<button type="button" disabled={busy} onClick={run}>{busy?"عم حلل الجهازين…":"🏆 جاهز للمقارنة"}</button>}</div><p className="compare-quota-note">رصيدك: {quota?.remaining ?? 10} من 10 مقارنات هالشهر.</p></>}</div></div>}</>;}
